

trigger:
- master

pool:
  vmImage: ubuntu-latest
jobs:
- job: job1
  steps:
  - script: echo Job1!
    displayName: 'Run a one-line script'
- job: job2
  dependsOn: job1
  steps:
  - script: echo Hello Job2!
    displayName: 'Run a multi-line script'
- job: job3
  dependsOn: job2
  steps:
  - script: echo Hello Job3!
    displayName: 'Run a one-line script'